### ISSUE TITLE
DeliveryMethod service - incorrect API url

### ISSUE THREAD

**Issue by b3da-cz** [mallgroup/mpapi-client-php#12] opened 2018-10-29 09:36 UTC
Please update DeliveryMethod service PATH (ln. 27), the endpoint seems to be deprecated: {"status":"ERROR","message":"Resource not found"}

**Comment by danielrataj** [comment] 2021-05-10 09:24
This was probably caused by an internal issue with our API. Closing issue.

**Closed as completed by danielrataj** 2021-05-10 09:24 UTC
